---

kind: ServiceAccount
apiVersion: v1
metadata:
  name: kube-sidecar-injector
  labels:
    app.kubernetes.io/name: kube-sidecar-injector

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-sidecar-injector
  labels:
    app.kubernetes.io/name: kube-sidecar-injector
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["create", "get", "delete", "list", "patch", "update", "watch"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-sidecar-injector
  labels:
    app.kubernetes.io/name: kube-sidecar-injector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-sidecar-injector
subjects:
  - kind: ServiceAccount
    name: kube-sidecar-injector
    namespace: default
